### ISSUE TITLE
Widok szczegółowy zamówienia

### ISSUE THREAD

**Issue by dolejnik** [kret11/IT_APP_WT1855_PIFS_mobile#1]
LG G3:
![screenshot_2016-04-18-23-49-25](https://cloud.githubusercontent.com/assets/17503168/14621080/a6a838a2-05c0-11e6-9ba5-dbfd0f704e6a.png)
Device Brand i End date nachodzą na siebie.
Jeżeli któreś pole jest puste lub nie występuje to nie powinniśmy wyświetlać 'null'.
Labelki opisujące property powinny być pogrubione lub w inny sposób wyróżnione.

**Comment by mac-b-71** [comment]
Na większych ekranach wyświetla poprawnie, ale jeszcze poprawie, reszta uwag też jak najbardziej trafna, poprawię, dzięki

**Comment by dolejnik** [comment]
LG G3 ma 5.5 cala, więc nie wiem na jakich wielkich telefonach ty to testujesz ;)

**Comment by mac-b-71** [comment]
Heh testuje na S5, która ma 5.1 i poprawnie wyświetla :) może to zależy też od wersji androida

**Comment by mac-b-71** [comment]
Okej, poprawiono. Niedlugo wyjdzie wersja 1.03

**Comment by dolejnik** [comment]
Jeżeli któreś pole jest puste lub nie występuje to nie powinniśmy wyświetlać 'null'.

**Comment by mac-b-71** [comment]
Dzięki, poprawione, 1.04 gotowe :)
