### ISSUE TITLE
Widok listy zamówień

### ISSUE THREAD

**Issue by dolejnik** [kret11/IT_APP_WT1855_PIFS_mobile#2]
Powinien wyświetlać status oraz model telefonu. Id zamówienia nie jest nam do niczego potrzebne. Dodatkowo, jeżeli zamówienie jest zamknięte/anulowane to powinno przerzucić je na drugą listę lub odpowiednio oznaczyć.

**Comment by mac-b-71** [comment]
No właśnie tutaj nasuwa się problem czy można identyfikować jednoznaczne zamówienie przez model telefonu, co jeżeli klientowi psul się telefon 10x? W liście będzie miał same modele.  Sklepy internetowe zazwyczaj do identyfikacji używają numeru zamówienia - są one kilku cyfrowe. Może na liście będa wyświetlane  np numer_zamowienia, model_urządzenia?

**Comment by bozemojmaciej** [comment]
Tzn: numer_zamowienia, model_urządzenia

**Comment by dolejnik** [comment]
myślę, że id_zamowienia + model_urządzenia + status jest ok. spróbuj zmieścić, jak nie to zrób na potrzeby testów bez id_zamówienia

**Comment by mac-b-71** [comment]
Okej, poprawiono. Niedlugo wyjdzie wersja 1.03

**Comment by dolejnik** [comment]
na listingu zamówień chciałbym widzieć również producenta telefonu. na chwilę obecną można się pogubić która liczba co oznacza.
Format danych:
1. Nokia 3310 - Do odebrania
4. Samsung S6 - Oczekuje
5. Samsung S6 - Oczekuje

**Comment by mac-b-71** [comment]
Dzięki, poprawione :) :+1:
