### ISSUE TITLE
Zapamiętanie loginu i hasła

### ISSUE THREAD

**Issue by dolejnik** [kret11/IT_APP_WT1855_PIFS_mobile#3]
Chciałbym nie musieć się logować przy każdym uruchomieniu appki.
Przycisk wstecz nie powinien wylogowywać.

**Comment by mac-b-71** [comment]
No to co powinien robić przycisk wstecz? Nic? Zablokować go?

**Comment by dolejnik** [comment]
Powinien wyłączać appkę, ale bez wylogowywania

**Comment by mac-b-71** [comment]
No tutaj będzie trochę zabawy ale postaram się zrobić i wypuścić w wersji 1.03
