### ISSUE TITLE
Kolorowanie listingu zgłoszeń

### ISSUE THREAD

**Issue by dolejnik** [kret11/IT_APP_WT1855_PIFS_mobile#4]
Lista powinna być pokolorowana tak jak samo na webie.
Poczekaj z tym na zmianę kolumny Stan.

**Comment by mac-b-71** [comment]
Cześć Dawid, mógłbyś sprecyzować dla których statusów które kolorki? Mamy takie statusy:
0. Przyjęto -
1. Aktualizacja -
2. Oczekiwanie na części -
3. W naprawie -
4. Kontakt z klientem -
5. Zakończono -
6. Do odbioru - 
7. Odrzucono - 
![13249458_1091971150841073_42486718_n](https://cloud.githubusercontent.com/assets/17525316/15444050/304698a2-1eed-11e6-9ddb-946fe478107c.png)
